' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

title Sequence Diagram: Write Key to KVS Instance

participant "User" as actor
participant "«component» :kvs" as kvs

actor -> kvs: Set value for key
alt kvs-available
    kvs --> actor: Value set for key
else kvs-busy
    kvs --> actor: Resource-Busy-Error
end

@enduml
