' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

title Sequence Diagram: Read Data into Local Representation (KvsValue)

participant "User" as actor
participant "«component» :kvs" as kvs
participant "«component» :json" as json_parser
participant "«component» :filesystem" as fs

actor -> kvs: Open KVS

group Load defaults, then load KVS
    kvs -> fs: Read data file
    alt file-exists
        fs --> kvs: Data file content (JSON)
        kvs -> fs: Read data file hash
        alt hash-file-exists
            fs --> kvs: Data file hash
        else hash-file-read-error
            fs --> kvs: File-Error
            kvs --> actor: KVS-Hash-File-Read-Error
        end
        kvs -> kvs: Generate hash of data and compare
        alt hash-match-success
            kvs -> json_parser: Parse JSON data
        else hash-match-error
            kvs --> actor: Validation-Failed-Error
        end
        alt parsing-success
            json_parser --> kvs: Parsed JSON object (KvsValue)
        else parsing-error
            json_parser --> kvs: Parser-Error
            kvs --> actor: JSON-Parser-Error
        end
    else file-missing
        alt file-required
            fs --> kvs: File-Error
            kvs --> actor: KVS-File-Read-Error
        else file-optional
            kvs -> kvs: Start with empty data
        end
    end
end

kvs --> actor: KVS instance

@enduml
