' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

title Sequence Diagram: Read Key from KVS Instance

participant "User" as actor
participant "«component» :kvs" as kvs

actor -> kvs: Get value for key

alt key-exists
    kvs --> actor: Return value for key
else key-doesnt-exist
    kvs --> actor: Key-Not-Found-Error
end

@enduml
