' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

title Sequence Diagram: Flush Local Representation to Data File

participant "User" as actor
participant "«component» :kvs" as kvs
participant "«component» :json" as json_parser
participant "«component» :filesystem" as fs

actor -> kvs: Flush KVS

alt kvs-available
    kvs -> json_parser: Generate string from local representation

    alt json-string
        json_parser --> kvs: JSON data string
    else json-string-error
        json_parser --> kvs: JSON generator error
        kvs --> actor: JSON-Generator-Error
    end

    kvs -> kvs: Rotate snapshots

    alt snapshot-rotate-success
        kvs --> kvs: Snapshots rotated
    else snapshot-rotate-error
        kvs --> actor: Physical-Storage-Failure
    end

    kvs -> kvs: Create JSON data hash

    kvs -> fs: Write JSON data string to file

    alt file-write
        fs --> kvs: File successfully written
    else file-write-error
        fs --> kvs: Write error
        kvs --> actor: Physical-Storage-Failure
    end

    kvs -> fs: Write JSON data hash to file

    alt file-hash-write
        fs --> kvs: Hash file successfully written
        kvs --> actor: Flush successful
    else file-hash-write-error
        fs --> kvs: Write error
        kvs --> actor: Physical-Storage-Failure
    end
else kvs-busy
    kvs --> actor: Resource-Busy-Error
end

@enduml
